"""Upgrade Base

Revision ID: 1f53fa453a19
Revises: 35ebdb45525a
Create Date: 2023-07-13 14:07:55.005835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f53fa453a19'
down_revision = '35ebdb45525a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
