"""Upgrade Base

Revision ID: 35ebdb45525a
Revises: d619563e367a
Create Date: 2023-07-13 00:56:55.809740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35ebdb45525a"
down_revision = "d619563e367a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
