"""Upgrade Base

Revision ID: 5a757fa259d2
Revises: 1f53fa453a19
Create Date: 2023-07-13 14:13:37.675352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a757fa259d2'
down_revision = '1f53fa453a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
