"""Upgrade Donatios

Revision ID: 74d6b657b077
Revises: 5a757fa259d2
Create Date: 2023-07-13 14:14:16.941921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74d6b657b077"
down_revision = "5a757fa259d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
