"""Upgrade Base

Revision ID: d619563e367a
Revises: 626f730df892
Create Date: 2023-07-12 23:35:50.748229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd619563e367a'
down_revision = '626f730df892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
